# Generated by Django 4.0.5 on 2022-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
